### ISSUE TITLE
GMatch4py accuracy for graph edit distance

### ISSUE THREAD

**Issue by ffaez** [Jacobe2169/GMatch4py#11]
Hi,
I have a simple code to compare the computed graph edit distance with GMatch4py and also the graph_edit_distance function in networkx.
my code is as follows:

```import gmatch4py as gm
g1=nx.complete_graph(3)
g2=nx.complete_graph(4)
ged=gm.GraphEditDistance(1,1,1,1) # all edit costs are equal to 1
result=ged.compare([g1,g2],None)
print("GMatch4py output:\n", result)
print("networkx output:\n", nx.graph_edit_distance(g1,g2))
```
and the results are:
```
GMatch4py output:
 [[0. 7.]
 [7. 0.]]
networkx output:
 4.0
```

Would you please tell me what does each element of the output matrix of GMatch4py mean? Is 7 the edit distance computed by GMatch4py while the exact edit distance is 4? Is the performance and accuracy of GMatchpy low even for very small graphs or it is just an understanding mistake made by me?
Regards

**Comment by Jacobe2169** [comment]
Hi @ffaez,

Sorry about the delay (hope I'm not too late). The graph edit distance depends on how is computed each edition cost (e.g. delete the node A). Also, which algorithm is used to select which edit path is optimal (with a the lowest cost). In Gmatch4py, I implemented an algorithm that transpose the graph edit distance to an [Assignement Problem](https://en.wikipedia.org/wiki/Assignment_problem). In the networkx algorithm, it seems that they use an A* based algorithm [(article here)](https://hal.archives-ouvertes.fr/hal-01168816/document). Therefore, results can be different. So it's up to you to choose what method is more convenient to your problem.

Hope it helps,
Jacques
