### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Sultan91** [Jacobe2169/GMatch4py#12]
After running `python setup.py install `:
Terminal prompted with the following error:
`gmatch4py/mcs.cpp:27:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

**Comment by Jacobe2169** [comment]
Hi @Sultan91,

Do you have the c++ compilation `gcc` installed ?

**Comment by Sultan91** [comment]
':~/PycharmProjects/GraphBasedPlan/GMatch4py$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.11' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 
'

**Comment by Jacobe2169** [comment]
Do you have **python-dev** installed ?

**Comment by Sultan91** [comment]
Seems like so: 'python-dev is already the newest version (2.7.12-1~16.04)'

**Comment by Sultan91** [comment]
Yes you were right, for python3 `sudo apt-get install python3-dev`.
But also to avoid `import` errors:
`pip install numpy==1.16.1`
'pip install 'cython==0.29.5' --force-reinstall
'
