### ISSUE TITLE
Fresh Install doesn't work

### ISSUE THREAD

**Issue by daubin427** [Jacobe2169/GMatch4py#2]
Hello!

I'd love to try this out, but the installation appears to be broken.  Using Ubuntu18.04 I 

1. git clone https://github.com/Jacobe2169/GMatch4py.git
2. cd to GMatch4py
3.  sudo python3 setup.py install
4.  All is well

I build a simple setup.py to test:
```
from distutils.core import setup
from Cython.Build import cythonize

setup(
    ext_modules = cythonize("simpleGmatch4py.pyx")
)
```

I create a simpleGmatch4py.pyx:
```
# Gmatch4py use networkx graph 
import networkx as nx 
# import the GED using the munkres algorithm
import gmatch4py as gm

g1=nx.complete_bipartite_graph(5,4)
g2=nx.complete_bipartite_graph(6,4)

ged=gm.GraphEditDistance(1,1,1,1) # all edit costs are equal to 1
result=ged.compare([g1,g2],None)
print(result)
print("Hello")
```
I build inplace:
`python3 setup.py build_ext --inplace`

I then try to run it and get an error:
```
python3
>>import simpleGmatch4py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "simpleGmatch4py.pyx", line 4, in init simpleGmatch4py
    import gmatch4py as gm
  File "/usr/local/lib/python3.6/dist-packages/gmatch4py/__init__.py", line 4, in <module>
    from .ged.graph_edit_dist import *
  File "gmatch4py/ged/graph_edit_dist.pyx", line 1, in init GMatch4py.gmatch4py.ged.graph_edit_dist
ModuleNotFoundError: No module named 'GMatch4py'
```
Please help :)

**Comment by Jacobe2169** [comment]
Hi @daubin427, 

Did you run this code into the GMatch4py clone directory?

**Comment by daubin427** [comment]
Hello!
  No I ran it in a different directory.  I think the problem lies where call it GMatch4py in setup.py, but no where else is that used with that punctuation.

**Comment by Jacobe2169** [comment]
Did you try to run the same code in an Ipython or a python interpreter ?

**Comment by daubin427** [comment]
Yes.  See in the last line of my post I tried running it from a python3 interpreter.

**Comment by Jacobe2169** [comment]
I mean did you try to execute the code inside `simpleGmatch4py.pyx` (copy-paste) in interpreter ?

**Comment by Jacobe2169** [comment]
It is really weird oO I tried it on an Ubuntu and it's working oO 

I did the same thing you did in VirtualEnv, could you run the following commands :
```
# if don't have virtualenv, do: sudo pip3 install virtualenv
virtualenv -p python3 test_gmatch4py
cd test_gmatch4py
source bin/activate
pip install numpy networkx scikit-learn ipython cython scipy
mkdir install
cd install
git clone https://github.com/Jacobe2169/GMatch4py.git
cd GMatch4py
python setup.py install
cd ../..
nano setup.py # paste code
nano simpleGmatch4py.pyx # paste code
python setup.py build_ext --inplace
python # execute your script
```

**Comment by daubin427** [comment]
Hi,

  I'm behind a proxy and running virtualenv behind it is just not working :(  

  During the setup is there anything that goes out to the network?  Perhaps due to my proxy this 
is the culprit?

**Comment by daubin427** [comment]
I got past the proxy issue I think.  However in my bin directory there was no activate.  Skipping past that I got this far:

git clone https://github.com/Jacobe2169/GMatch4py.git
Cloning into 'GMatch4py'...
remote: Counting objects: 234, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 234 (delta 11), reused 16 (delta 8), pack-reused 207
Receiving objects: 100% (234/234), 59.98 KiB | 4.00 MiB/s, done.
Resolving deltas: 100% (137/137), done.
daubin@ubuntu:~/test_gmatch4py/install$ cd GMatch4py
daubin@ubuntu:~/test_gmatch4py/install/GMatch4py$ python setup.py install
gmatch4py/ged/graph_edit_dist.pyx: cannot find cimported module '..base'
gmatch4py/ged/graph_edit_dist.pyx: cannot find cimported module '.abstract_graph_edit_dist'
gmatch4py/ged/graph_edit_dist.pxd: cannot find cimported module '.abstract_graph_edit_dist'
gmatch4py/ged/greedy_edit_distance.pyx: cannot find cimported module '.graph_edit_dist'
gmatch4py/ged/bipartite_graph_matching_2.pyx: cannot find cimported module '..base'
gmatch4py/ged/abstract_graph_edit_dist.pyx: cannot find cimported module '..base'
gmatch4py/ged/abstract_graph_edit_dist.pxd: cannot find cimported module '..base'
gmatch4py/ged/hausdorff_edit_distance.pyx: cannot find cimported module '..base'
gmatch4py/kernels/weisfeiler_lehman.pyx: cannot find cimported module '..base'
gmatch4py/bon.pyx: cannot find cimported module '.base'
gmatch4py/jaccard.pyx: cannot find cimported module '.base'
gmatch4py/vertex_edge_overlap.pyx: cannot find cimported module '.base'
gmatch4py/mcs.pyx: cannot find cimported module '.base'
gmatch4py/vertex_ranking.pyx: cannot find cimported module '.base'
gmatch4py/bag_of_cliques.pyx: cannot find cimported module '.base'
Compiling gmatch4py/ged/graph_edit_dist.pyx because it changed.
Compiling gmatch4py/ged/greedy_edit_distance.pyx because it changed.
Compiling gmatch4py/ged/bipartite_graph_matching_2.pyx because it changed.
Compiling gmatch4py/ged/abstract_graph_edit_dist.pyx because it changed.
Compiling gmatch4py/ged/hausdorff_edit_distance.pyx because it changed.
Compiling gmatch4py/kernels/random_walk_kernel.pyx because it changed.
Compiling gmatch4py/kernels/weisfeiler_lehman.pyx because it changed.
Compiling gmatch4py/kernels/shortest_path_kernel.pyx because it changed.
Compiling gmatch4py/bon.pyx because it changed.
Compiling gmatch4py/jaccard.pyx because it changed.
Compiling gmatch4py/vertex_edge_overlap.pyx because it changed.
Compiling gmatch4py/base.pyx because it changed.
Compiling gmatch4py/mcs.pyx because it changed.
Compiling gmatch4py/vertex_ranking.pyx because it changed.
Compiling gmatch4py/deltacon.pyx because it changed.
Compiling gmatch4py/bag_of_cliques.pyx because it changed.
Compiling gmatch4py/alg_types.pyx because it changed.
Compiling gmatch4py/helpers/reader.pyx because it changed.
[ 1/18] Cythonizing gmatch4py/alg_types.pyx
[ 2/18] Cythonizing gmatch4py/bag_of_cliques.pyx
[ 3/18] Cythonizing gmatch4py/base.pyx
[ 4/18] Cythonizing gmatch4py/bon.pyx
[ 5/18] Cythonizing gmatch4py/deltacon.pyx
[ 6/18] Cythonizing gmatch4py/ged/abstract_graph_edit_dist.pyx
[ 7/18] Cythonizing gmatch4py/ged/bipartite_graph_matching_2.pyx
[ 8/18] Cythonizing gmatch4py/ged/graph_edit_dist.pyx
[ 9/18] Cythonizing gmatch4py/ged/greedy_edit_distance.pyx
[10/18] Cythonizing gmatch4py/ged/hausdorff_edit_distance.pyx
[11/18] Cythonizing gmatch4py/helpers/reader.pyx
[12/18] Cythonizing gmatch4py/jaccard.pyx
[13/18] Cythonizing gmatch4py/kernels/random_walk_kernel.pyx
[14/18] Cythonizing gmatch4py/kernels/shortest_path_kernel.pyx
[15/18] Cythonizing gmatch4py/kernels/weisfeiler_lehman.pyx
[16/18] Cythonizing gmatch4py/mcs.pyx
[17/18] Cythonizing gmatch4py/vertex_edge_overlap.pyx
[18/18] Cythonizing gmatch4py/vertex_ranking.pyx
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by daubin427** [comment]
I FOUND IT!!!!  WHOOT!!!!  Issue was not having scikit-learn.  Once I pipped that all was good.  Odd error to see without it.  Thank you for your super prompt and helpful tips to locate it :)  So happy!

**Comment by Jacobe2169** [comment]
Great ! ;)

**Comment by daubin427** [comment]
I created a setup.py for you so that even lazy eyes can't screw up the install ;)  All you have to do is fill out the #List of dependencies section at the top.  Thanks again :)
[setup.py.txt](https://github.com/Jacobe2169/GMatch4py/files/2390357/setup.py.txt)
