### ISSUE TITLE
What is the order of the costs in GraphEditDistance?

### ISSUE THREAD

**Issue by emmanuelasso** [Jacobe2169/GMatch4py#21]
Hi, in the readme it appears that:

`ged=gm.GraphEditDistance(1,1,1,1) # all edit costs are equal to 1`

The costs are adding and removing nodes and edges?
but what is the order of the costs?

**Comment by olhakholod** [comment]
Hi, the order is the following:

node deletion = 1, node insertion = 1,  edge deletion = 1, edge insertion = 1
