### ISSUE TITLE
ModuleNotFoundError: No module named 'skipgram'

### ISSUE THREAD

**Issue by gui-li** [Jacobe2169/GMatch4py#28]
When I try to import gmatch4py, the below error happens:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-789a2ae4f894> in <module>
----> 1 import gmatch4py as gm

c:\users\XXX\appdata\local\programs\python\python39\lib\site-packages\gmatch4py\__init__.py in <module>
     13 # Graph Embedding import
     14 from .embedding.graph2vec import *
---> 15 from .embedding.deepwalk import *
     16 from .embedding.node2vec import *
     17 # Helpers import

gmatch4py\embedding\deepwalk.pyx in init gmatch4py.embedding.deepwalk()

ModuleNotFoundError: No module named 'skipgram'
```

**Comment by JeanKaddour** [comment]
Same here, but I commented this import out since I'm only interested in GED and that worked.

**Comment by Trinkwassersprudler** [comment]
Also the same here. Tested on Windows and Linux.

**Comment by doralune** [comment]
I fix

https://github.com/Jacobe2169/GMatch4py/blob/aec78a2ca76f4098d867dc30384ce843e7cf027a/gmatch4py/embedding/deepwalk.pyx#L31

to

```python
from .skipgram import Skipgram
```

then reinstall and it works !!

**Comment by kodama-codes** [comment]
Thanks @doralune. I had to install it twice (first time got an error) but then it worked like a charm. Thanks alot.

**Comment by doralune** [comment]
Hi @kodama-codes
The error came from that the latest gensim library no longer has Vocab.
I downgraded to gensim==3.8.3 and then it worked.

**Comment by kodama-codes** [comment]
Ahoi @doralune 

Perfect, now it workes like a charm. Thx alot!

**Comment by chilligerchief** [comment]
gensim 3.8.3 can not easily be installed on newer systems. Modern gcc won't compile it. Please don't expect me to downgrade gcc as well^^. Any easy way to fix this, or is this library dead?

**Comment by Anmario** [comment]
> I fix
> 
> https://github.com/Jacobe2169/GMatch4py/blob/aec78a2ca76f4098d867dc30384ce843e7cf027a/gmatch4py/embedding/deepwalk.pyx#L31
> 
> to
> 
> ```python
> from .skipgram import Skipgram
> ```
> 
> then reinstall and it works !!

I did that, but still having the very first Error, with (ModuleNotFoundError: No module named 'skipgram')

Starting to lose faith
Please Help!

**Comment by doralune** [comment]
@Anmario It should be different error after fixing something. Please give more details for reproducing the error.

**Comment by doralune** [comment]
> gensim 3.8.3 can not easily be installed on newer systems. Modern gcc won't compile it. Please don't expect me to downgrade gcc as well^^. Any easy way to fix this, or is this library dead?

GMatch4py is not updated for 3 years ? and still uses the old gensim, so we don't have much choice. For me, I use the docker container for running old stuff.

**Comment by Anmario** [comment]
> @Anmario It should be different error after fixing something. Please give more details for reproducing the error.

That's logic, but I get in the both cases the same below.

<frozen importlib._bootstrap>:228: UserWarning: To obtain optimal results install the Cython 'munkres' module at  https://github.com/jfrelinger/cython-munkres-wrapper
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_27028/812984187.py in <module>
      1 import networkx as nx
----> 2 import gmatch4py as gm
      3 1+1

~\anaconda3\lib\site-packages\gmatch4py\__init__.py in <module>
     13 # Graph Embedding import
     14 from .embedding.graph2vec import *
---> 15 from .embedding.deepwalk import *
     16 from .embedding.node2vec import *
     17 # Helpers import

gmatch4py\embedding\deepwalk.pyx in init gmatch4py.embedding.deepwalk()

ModuleNotFoundError: No module named 'skipgram'

**Comment by chilligerchief** [comment]
Hello all, I took the time to make a fork of this library and remove all code that is not related to graph edit distance and cleaned it up, so it has no legacy dependencies.
If you want to use only graph edit distances and no other features feel free to use my fork. It should easier to maintain, since it has much less dependencies.
Check it out at [https://github.com/chilligerchief/GED4py](https://github.com/chilligerchief/GED4py)

**Comment by jacquesfize** [comment]
Hi all ! 

Sorry for being silent for many years...I've been busy and did not have much time for GMatch4py. Thanks to you all for helping peoples in need when it comes to make GMatch4py work ! 

I push few modifications that integrates solutions proposed in this feed. 

Bests,
Jacques
