### ISSUE TITLE
Deepwalk is a node embedding algorithm.

### ISSUE THREAD

**Issue by benedekrozemberczki** [Jacobe2169/GMatch4py#6]
Deepwalk is a node embedding algorithm (graph embedding ≠ node embedding). As each run of a node embedding can be rotated with an orthogonal rotation matrix doing any sort of comparison of two node embedding is totally meaningless. I am also somewhat surprised to see large blocks of code from my graph2vec repository.

**Comment by Jacobe2169** [comment]
Hi @benedekrozemberczki,

You're right, DeepWalk isn't a graph embedding algorithm, I'll change that in the next version.

As for graph2vec, I reused your code and join a reference to it (See [here])(https://github.com/Jacobe2169/GMatch4py/blob/975af71a53496fc690d90ff89743e9dcdf688da3/gmatch4py/embedding/graph2vec.pyx#L170) ) Also, your paper is referenced in the README.

If you wish your repo to be explicitly referenced in the README page, let me know !

Bests,
Jacques
