### ISSUE TITLE
Edit Path

### ISSUE THREAD

**Issue by safreita1** [Jacobe2169/GMatch4py#7]
Is it possible to get the edit path (not just the distance) between two graphs for any of the graph edit algorithms?

**Comment by Jacobe2169** [comment]
Hi @safreita1,

The edit path is not accessible (for now) outside of the edit distance computation. 

The `edit_costs()`  function is only accessible within the `AbstractGraphEditDistance` because of the `cdef` method type. 
https://github.com/Jacobe2169/GMatch4py/blob/8d0f09467986a398432e2a902262e8ce8bfc6cac/gmatch4py/ged/abstract_graph_edit_dist.pyx#L55

If you wish to access it, you can replace `cdef` by `cpdef` in the `edit_costs()` declaration. I'll make the change in the next commit.

Bests,
Jacques

**Comment by r03ert0** [comment]
Hello,
I'd be also very interested in accessing the edit path : )

**Comment by Jacobe2169** [comment]
Hi @r03ert0  and @safreita1,

I just pushed a new version with an `edit_path()` method that return the edit path.

Bests,
Jacques

**Comment by r03ert0** [comment]
Thank you very much @Jacobe2169 !!

Is this the correct way of using the algorithm?

```
import networkx as nx 
import gmatch4py as gm

g1=nx.complete_bipartite_graph(5,4) 
g2=nx.complete_bipartite_graph(6,4)

aged=gm.ged.abstract_graph_edit_dist.AbstractGraphEditDistance(1,1,1,1)
result=aged.compare([g1,g2],None) # I get an error at this point
print(result)
aged.edit_path(result)
```

The error I'm getting is "Exception ignored in: 'gmatch4py.ged.abstract_graph_edit_dist.AbstractGraphEditDistance.substitute_cost'
NotImplementedError:"

**Comment by Jacobe2169** [comment]
Don't use the `AbstractGraphEditDistance, it's an abstract class ;) Here is an example :

```python
import networkx as nx 
import gmatch4py as gm

g1=nx.complete_bipartite_graph(5,4) 
g2=nx.complete_bipartite_graph(6,4)

# Instance used to compute the Graph Edit Distance
ged=gm.GraphEditDistance(1,1,1,1)

# Gmatch4py use it's own graph structure, to use the edit_path() methods
# you first need to parse them
from gmatch4py.helpers.general import parsenx2graph
GS= parsenx2graph([g1,g2])

# Then use the methods 
ged.edit_path(GS[0],GS[1])


"""
# Result
(array([2., 0., 0., 0., 0., 2., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., # edit path
        0., 7.]),
 array([[0.00000000e+00, 9.22337204e+18, 9.22337204e+18, 9.22337204e+18, # cost matrix
         9.22337204e+18, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00,
         2.00000000e+00, 9.00000000e+00, 5.00000000e+00, 9.22337204e+18,
         9.22337204e+18, 9.22337204e+18, 9.22337204e+18, 9.22337204e+18,
         9.22337204e+18, 9.22337204e+18, 9.22337204e+18],
        ...
        [9.22337204e+18, 9.22337204e+18, 9.22337204e+18, 9.22337204e+18,
         9.22337204e+18, 9.22337204e+18, 9.22337204e+18, 9.22337204e+18,
         9.22337204e+18, 7.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]),
 array([[False, False, False, False, False,  True, False, False, False, # result from the munkres algorithm
         False, False, False, False, False, False, False, False, False,
         False],
        [False,  True, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False],
        ...
        [False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
          True],
        [False, False, False, False, False, False, False, False, False,
          True, False, False, False, False, False, False, False, False,
         False]]))
"""
```

The `edit_path` will soon be updated to directly takes `networkx` Graph as input (the parsing will be done within the method ;))

Hope it helps.

**Comment by r03ert0** [comment]
cool! that works \o/

Here's the result I get for the edit path:
```
Edit path:
[2. 0. 0. 0. 0. 2. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 7.]
```

But I don't get True/False values for the Munkres assignment. I get integer values:
```
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18]), array([ 5,  1,  2,  3,  4,  0,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17,
       18,  9]))
```

How do I interpret these values? The edit path values are costs, right? Is there a way of knowing what were the edits? (node_del, node_ins, edge_del, edge_ins). How can I figure out which nodes in G1 were made to correspond with which nodes in G2?

**Comment by Jacobe2169** [comment]
It depends on the munkres assignment function you're using (cython version or spicy version). In Scipy, version the output is a set of two arrays corresponding to x and y positions in the cost matrix. In the cython, it's a boolean array. 

In both cases, it's pinpoint the position of the optimal assignments in the cost matrix. As for the node <-> cost-matrix association (nodes order is the same as in your networkx input, use `list(G.nodes())`), it look like this :

![cost_matrix](https://user-images.githubusercontent.com/4259846/58087053-15ba9f00-7bc0-11e9-81ae-23203ac20835.png)

**Comment by r03ert0** [comment]
thank you @Jacobe2169 for the figure ! It's very clear now : )

**Comment by Sultan91** [comment]
![image](https://user-images.githubusercontent.com/16382530/62778953-7fa95d00-baba-11e9-87f4-0dd9e9dc0477.png)
How do we treat this part of matrix if we have `true` values inside?

**Comment by Sultan91** [comment]
BTW. Is it possible to obtain which edges should be added/deleted/substituted?

**Comment by Jacobe2169** [comment]
Hi @Sultan91,

The values on the bottom-right of the matrix correspond to the "do nothing" graph edition.

As for knowing which edges is added/deleted or substituted, it is currently not implemented within the `GraphEditDistance()`. You can modify the GraphEditDistance class or  you can create a new class that inherit from `AbstractGraphEditDistance` and store such information during the cost matrix computation. You can use the following template to do so :

```python
# -*- coding: UTF-8 -*-


import networkx as nx
from gmatch4py.ged.abstract_graph_edit_dist cimport AbstractGraphEditDistance

cdef class ExampleCustomGraphEditDistance(AbstractGraphEditDistance):

    def __init__(self,node_del,node_ins,edge_del,edge_ins,weighted=False):
        AbstractGraphEditDistance.__init__(self,node_del,node_ins,edge_del,edge_ins)
        self.weighted=weighted
        
    cpdef double substitute_cost(self, node1, node2, G, H):
        return 1

    cdef double delete_cost(self, int i, int j, nodesG, G):
       return 1

    cdef double insert_cost(self, int i, int j, nodesH, H):
        return 1
```


Best,
Jacques
