### ISSUE TITLE
HED returns 0

### ISSUE THREAD

**Issue by computerquest** [Jacobe2169/GMatch4py#8]
I have a bunch of graphs I know to be unique, and when I calculate GED using GraphEditDistance it returns non-zero values as expected. However when using HED instead of GraphEditDistance, it outputs only 0.

````
ged = gm.HED(1, 1, 1, 1) 
result = ged.compare(all_graph, None)
print(*result)
````

Is my code wrong or is there an issue with the library?

**Comment by Jacobe2169** [comment]
Hi @computerquest,

It is weird... can you give me an example of the graphs you're using ?

Bests Jacques
